<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>

    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Embedded/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="7.2.3" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);EMBER_SAFETY_CHECKS</DefineConstants>
  </PropertyGroup>
</Project>
